web:
   image: php:5.6-apache
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
     - "443:443"
   links:
     - db
   volumes:
     - ./app/www:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: suyay
    MYSQL_PASSWORD: 12345
    MYSQL_DATABASE: suyay
  ports:
    - "8889:3306"
